rtr-nettest/open-rmbt-ios

- Sources/Base.lproj/TestStoryboard.storyboard
- Sources/RMBTIntroViewController.m
- Sources/RMBTLoopModeTestViewController.m
- Sources/RMBTQoSDNSTest.m
for now,
minimal timeout is 1 second
if we have some error and it has happened early than timeout then it was an error
> Fix dns test timeout

- Resources/Base.lproj/Localizable.strings
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Sources/RMBTBaseTestViewController.m
- Sources/Test/RMBTQoSProgressViewController.m
- Sources/TestStoryboard.storyboard
- add translations for test screen
> ONT-3915/translate-test-screen

- Sources/History/Cells/RMBTHistoryGraphCell.xib
- Sources/RMBTBaseTestViewController.h
- Sources/RMBTBaseTestViewController.m
- Sources/RMBTGaugeView.swift
- Sources/Test/RMBTTestViewController.swift
- Sources/Test/View/RMBTTestLandscapeView.swift
- Sources/Test/View/RMBTTestPortraitView.swift
- fix graph in result screen
- change percentage for phases
> Ont 3748/fix percentage

- Sources/Speed.swift
> ONT-4515/fix-graph

- Sources/Test/View/RMBTTestLandscapeView.swift
- Sources/Test/View/RMBTTestLandscapeView.xib
- Sources/Test/View/RMBTTestPortraitView.swift
- fix right side on test screen for small screens
> Fix right side on test screen for small screens

- Resources/Base.lproj/Localizable.strings
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Sources/MainStoryboard.storyboard
- Sources/RMBTBaseTestViewController.m
- Sources/RMBTSettingsViewController.m
- Sources/Test/RMBTTestViewController.swift
- Sources/Test/View/RMBTTestLandscapeView.swift
fix percents of test with qos
fix scroll for qos tests fix alert on loop mode
reorder settings options
> Ont 3748 fix percents

- Resources/Base.lproj/Localizable.strings
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Sources/ConnectivityService.swift
- Sources/MainStoryboard.storyboard
- Sources/RMBTHistoryResult.m
- Sources/RMBTQoSControlConnection.m
- Sources/RMBTSettingsViewController.m
- fix qos tests 
- fix values up down and ping after test
- add location indicator fix ip
> Ont 3529/fix ip

- Resources/Base.lproj/Localizable.strings
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Sources/History/RMBTHistoryFiltersOptionsViewController.swift
- Sources/MainStoryboard.storyboard
- Sources/Map/RMBTMapOptionsFilter2ViewController.swift
- Sources/Map/RMBTMapOptionsTypes2ViewController.swift
- Sources/Map/RMBTMapOverlays2ViewController.swift
> ONT-4723-fix-translations

- Sources/RMBTSettingsViewController.m
- Sources/RMBTSettingsViewController.swift
- disable ipv4 when disable expert mode
- disable ipv6 when disable debug mode
> ONT-4677-disable-ipv4

- Sources/Map/RMBTMap2ViewController.swift
- add zoom after search something
> ONT-3759/fix-search-on-map

- RMBT.xcodeproj/project.pbxproj
- Sources/History/Cells/RMBTHistoryPingGraphCell.swift
- Sources/History/Cells/RMBTHistoryPingGraphCell.xib
- Sources/History/Cells/RMBTHistorySpeedGrapshCell.swift
- Sources/History/RMBTHistoryResult2ViewController.swift
- Sources/RMBTHistoryPingGraph.swift
- Sources/RMBTHistoryResult.h
- Sources/RMBTHistoryResult.m
- Sources/RMBTPingGraphView.swift
- Sources/Responses/RMBTOpenDataResponse.swift
- implement ping graph and add to history result screen
> ONT-3763/add-ping-graph

- RMBT.xcodeproj/project.pbxproj
- RMBT.xcodeproj/xcshareddata/xcschemes/RMBT.xcscheme
- Sources/MainStoryboard.storyboard
- Sources/Map/RMBTMapOptionsTypesViewController.swift
- Sources/Map/RMBTMapOptionsViewController.swift
- Sources/Map/RMBTMapViewController.swift
- Sources/Models/RMBTMapOptions.swift
- Sources/Models/RMBTMapOptionsFilter.swift
- Sources/RMBTMapServer.swift
- Sources/Responses/MapOptionResponse.swift
> ONT-4759/update-interface-icon-identifier

- Sources/RMBTConnectivity.swift
> ONT-4680/fix-crash

- Sources/Common/UIAlertController+Additions.swift
- Sources/Intro/RMBTLoopModeSettingsViewController.swift
- Sources/Map/RMBTSearchMapViewController.swift
- Sources/RMBTBaseTestViewController.swift
- Sources/RMBTSettingsViewController.swift
- Sources/RMBTTestResult.swift
- Sources/Test/RMBTTestViewController.swift
- fix idletimer and fix warnings
> ONT-4681/fix-idle-timer

- Sources/Common/CLLocation+Additions.swift
- fix format position in location popup
> ONT-4817/fix-format-position

- Sources/Views/RMBTIntroPortraitView.swift
> ONT-4818/mirror-wave

- Sources/History/Cells/RMBTHistoryLoopCell.swift
- Sources/RMBTBaseTestViewController.swift
- Sources/Test/RMBTTestViewController.swift
- add gesture for loop mode cell
> ONT-4829/expend-loopmode-all-line

- Sources/RMBTSettingsViewController.swift
> ONT-4831/only-2-hours-by-default

- Sources/MainStoryboard.storyboard
- Sources/RMBTSettingsViewController.swift
- fix selection UITextField when we tap on the cell
> ONT-4937/fix-edit-loopmode-settings

- Sources/RMBTIntroViewController.swift
> ONT-4957/fix-speed-location

- Sources/Test/RMBTTestViewController.swift
- fix increase frequently for diagram updates
> ONT-4834/increase-frequently-updates-for-diagram

- RMBT.xcodeproj/xcshareddata/xcschemes/RMBT.xcscheme
- Resources/en.lproj/terms_conditions_long.html
- Sources/RMBTModalWebViewController.swift
- Sources/RMBTSettingsViewController.swift
- fix terms and condition UI and url
> fix terms and condition UI and url

- Sources/RMBTControlServer.swift
- Sources/RMBTSettingsViewController.swift
- Sources/Requests/BasicRequest.swift
- Sources/Responses/Responses.swift
add parse terms and condition url from settings request
> add parse terms and condition url from settings request

- RMBT.xcodeproj/project.pbxproj
- Sources/RMBTSettings.swift
- Sources/RMBTSettingsViewController.swift
- Sources/RMBTTestRunner.swift
- Sources/Test/RMBTTestViewController.swift
> ONT-4831/fix-skip-qos

- Sources/Intro/RMBTLoopModeSettingsViewController.swift
> ONT-4939/Store-values-loop-mode

- Resources/Base.lproj/Localizable.strings
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Sources/MainStoryboard.storyboard
- Sources/RMBTIntroViewController.swift
- Sources/Views/RMBTPopupViewController.swift
- address is not available for ipv6
> ONT-5081/address-is-not-available

- Sources/RMBTSettingsViewController.swift
- Sources/RMBTTOSViewController.swift
- Sources/UIViewController+ModalBrowser.swift
- open url in external browser
> open url in external browser

- Sources/History/Cells/RMBTQOEItemCell.xib
> ONT-5084/fix-qoe-squares

- Resources/Base.lproj/Localizable.strings
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Sources/MainStoryboard.storyboard
- Sources/RMBTStatsViewController.swift
- remove toolbar on statistics page
> ONT-5085/remove-toolbar-statistics-page

- RMBT.xcodeproj/project.pbxproj
- Sources/RMBTSettingsViewController.swift
- go to location settings when tap on location in settings app
> ONT-4956/fix-go-to-location-settings

- Sources/RMBTHelpers.swift
- Sources/Test/RMBTTestViewController.swift
- Sources/Test/View/RMBTTestLandscapeView.xib
- Sources/Test/View/RMBTTestPortraitView.swift
- Sources/Test/View/RMBTTestPortraitView.xib
- add coloring for ping up down
> ONT-5139/colors-for-ping-up-down

- Resources/Base.lproj/Localizable.strings
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Sources/MainStoryboard.storyboard
- Sources/RMBTHelpers.swift
- Sources/RMBTSettingsViewController.swift
- remove location toggle from settings
> ONT-5140/location-toggle

- Sources/Intro/RMBTLoopModeSettingsViewController.swift
- Sources/RMBTSettingsViewController.swift
rebind textfileds for loop mode
refactoring
fix development mode
> ONT-5193/development_mode_fix

- Sources/RMBTBaseTestViewController.swift
- Sources/RMBTQoSControlConnection.swift
- Sources/RMBTQoSTestRunner.swift
- Sources/RMBTTestRunner.swift
- Sources/Test/RMBTQoSProgressViewController.swift
- Sources/Test/RMBTTestViewController.swift
- Sources/Test/View/RMBTTestPortraitView.xib
- fix counter for tests in loop mode
> ONT-5195/fix-counter-of-tests

- Sources/RMBTQoSWebTest.swift
- Sources/Test/RMBTTestViewController.swift
- fix change waiting logic in loop mode
> ONT-5196/change-waiting-next-test

- RMBT.xcodeproj/project.pbxproj
- Sources/RMBTControlServer.swift
- Sources/Test/RMBTTestViewController.swift
> Ont 5231/fix loop mode with zero values

- Sources/MainStoryboard.storyboard
- Sources/Test/RMBTTestViewController.swift
- Sources/TestStoryboard.storyboard
change sample duration for graph speed, upload and download
> ONT-4834/change-samples-duration-and-delay

- RMBT.xcodeproj/project.pbxproj
- Sources/RMBTHelpers.swift
- Sources/Test/RMBTTestViewController.swift
- refactoring fdSet, fdClr, fdIsSet
> try fix crash

- RMBT.xcodeproj/project.pbxproj
- Sources/RMBTBaseTestViewController.swift
- Sources/RMBTHistoryPingGraph.swift
- Sources/RMBTPingGraphView.swift
- Sources/RMBTTestRunner.swift
- Sources/RMBTTestWorker.swift
- Sources/Test/RMBTTestViewController.swift
- Sources/Test/View/RMBTTestLandscapeView.xib
- Sources/Test/View/RMBTTestPortraitView.swift
- Sources/Test/View/RMBTTestPortraitView.xib
> Ont 5298/dynamic-ping

- Sources/Requests/BasicRequest.swift
- add client_software_version field to /result request
> ONT-5506/add_client_software_version

- Sources/History/RMBTHistoryResultViewController.swift
- Sources/RMBTBlockTypes.swift
- Sources/RMBTHistoryResult.swift
- add alert when result can't be loaded
> ONT-5436/add_alert_when_result_not_loaded

- Sources/History/RMBTHistoryResultViewController.swift
- fix crash when click shared button on iPad
> ONT-5560/crash-ipad-share-button

- Sources/Map/RMBTMapViewController.swift
show details of test in browser
> ONT-5571/open-details-in-browser

- RMBT.xcodeproj/project.pbxproj
- Sources/Map/RMBTMapViewController.swift
- Sources/RMBTSettingsViewController.swift
- Sources/RMBTStatsViewController.swift
- implement internal web controller
> ONT-5571/open-link-in-internal-browser

- RMBT.xcodeproj/project.pbxproj
- Resources/Base.lproj/Localizable.strings
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Sources/RMBTIntroViewController.swift
- Sources/RMBTSettings.swift
- Sources/UserDefaults+Additions.swift
- Sources/Views/RMBTIntroLandscapeView.xib
- Sources/Views/RMBTIntroPortraitView.swift
- Sources/Views/RMBTIntroPortraitView.xib
- Sources/Views/TopPopoverView.swift
This PR adds a popup message to display a short tip for the "Start Test' button.
This tip appears after 2 secs and disappears after 4 secs. After it gets shown 5 times in total or after the "Start Test" button is tapped, it is never shown again.
The screen area around the popup message is active so the test can be immediately started by tapping once on the button.
> Display help tip for Start Test button

- Resources/Base.lproj/Localizable.strings
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Sources/Views/RMBTIntroLandscapeView.xib
- Sources/Views/RMBTIntroPortraitView.xib
This PR fills-in missing localization for the Intro screen title name
> Localize the title of the Intro screen

- Sources/RMBTHistorySpeedGraph.swift
This PR updates the way history charts are computed.
Previously the value for each point in time was computed as an average speed from the very beginning of the total time interval. Resulting in the chart line being very flat.
Now the speed is being computed for each 100ms time interval individually. Now the chart looks more similar to the chart on the Test screen as well as a chart on the Web displaying the same test result.
> Fix computation of history charts

- Sources/MainStoryboard.storyboard
- Sources/RMBTSettingsViewController.swift
- Sources/Views/RMBTIntroLandscapeView.xib
This PR improves UI in the landscape model.
It changes the UI for the Intro screen to look better.
It fixes issues in the Settings screen in landscape orientation
> Improvements to landscape mode

- Sources/History/RMBTHistoryDownloadViewController.swift
- Sources/History/RMBTHistoryResultViewController.swift
- Sources/RMBTControlServer.swift
- Sources/TestExportFormat.swift
- Increase timeout
- download max 100 tests
- improve error handling
> Fixes for downloading large number of test
